import type { Packet, UserHint } from "core";

// used for populating temporary data until we get real data
function hexToArrayBuffer(hexArray: string[]): Uint8Array {
    const buffer = new ArrayBuffer(hexArray.length);
    const view = new Uint8Array(buffer);
    hexArray.forEach((hex, i) => {
        view[i] = Number(hex);
    });
    return view;
}

export function convertPayloads(data: any[]): (Packet | UserHint)[] {
    return data.map((item) => {
        if (item.type.startsWith("DATA")) {
            const inferredData = !!item.inferred ? item.inferred : null;
            return {
                ...item,
                timestamp: parseInt(item.timestamp),
                payload: new Uint8Array(item.payload.data).buffer, // convert array to ArrayBuffer
                inferred: inferredData,
            } as Packet;
        } else {
            return {
                ...item,
                timestamp: parseInt(item.timestamp),
                payload: item.payload,
            };
        }
    });
}

export function getPlaceholderData(): Array<Packet | UserHint> {
    return [
        {
            type: "DATA-UP",
            timestamp: 1,
            payload: hexToArrayBuffer([
                "0xa1",
                "0x02",
                "0x03",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
            ]),
        },
        {
            type: "USER-HINT",
            timestamp: 2,
            payload: "Woah guys this is a message",
        },
        {
            type: "DATA-DOWN",
            timestamp: 3,
            payload: hexToArrayBuffer([
                "0x44",
                "0x52",
                "0x4f",
                "0x4e",
                "0x45",
                "0x20",
                "0x54",
                "0x45",
                "0x53",
                "0x54",
                "0x49",
                "0x4e",
                "0x47",
                "0x20",
                "0x46",
                "0x4c",
                "0x49",
                "0x47",
                "0x48",
                "0x54",
                "0x75",
                "0x77",
                "0x68",
                "0x64",
                "0x71",
                "0x75",
                "0x6f",
                "0x70",
                "0x6e",
                "0x77",
                "0x70",
                "0x75",
                "0x64",
                "0x55",
                "0x41",
                "0x53",
                "0x77",
                "0x71",
                "0x75",
                "0x6e",
                "0x64",
                "0x75",
                "0x71",
                "0x77",
                "0x75",
                "0x75",
                "0x55",
                "0x4e",
                "0x45",
                "0x52",
                "0x53",
                "0x54",
                "0x41",
                "0x4e",
                "0x44",
                "0x20",
                "0x4d",
                "0x45",
                "0x3f",
                "0x3f",
                "0x3f",
                "0x32",
                "0x33",
                "0x31",
                "0x31",
                "0x32",
                "0x33",
            ]),
        },
        {
            type: "DATA-UP",
            timestamp: 4,
            payload: hexToArrayBuffer([
                "0xa1",
                "0x02",
                "0x03",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
            ]),
        },
        {
            type: "USER-HINT",
            timestamp: 5,
            payload: "Woah guys this is a message",
        },
        {
            type: "DATA-DOWN",
            timestamp: 6,
            payload: hexToArrayBuffer([
                "0x44",
                "0x52",
                "0x4f",
                "0x4e",
                "0x45",
                "0x20",
                "0x54",
                "0x45",
                "0x53",
                "0x54",
                "0x49",
                "0x4e",
                "0x47",
                "0x20",
                "0x46",
                "0x4c",
                "0x49",
                "0x47",
                "0x48",
                "0x54",
                "0x75",
                "0x77",
                "0x68",
                "0x64",
                "0x71",
                "0x75",
                "0x6f",
                "0x70",
                "0x6e",
                "0x77",
                "0x70",
                "0x75",
                "0x64",
                "0x55",
                "0x41",
                "0x53",
                "0x77",
                "0x71",
                "0x75",
                "0x6e",
                "0x64",
                "0x75",
                "0x71",
                "0x77",
                "0x75",
                "0x75",
                "0x55",
                "0x4e",
                "0x45",
                "0x52",
                "0x53",
                "0x54",
                "0x41",
                "0x4e",
                "0x44",
                "0x20",
                "0x4d",
                "0x45",
                "0x3f",
                "0x3f",
                "0x3f",
                "0x32",
                "0x33",
                "0x31",
                "0x31",
                "0x32",
                "0x33",
            ]),
        },
        {
            type: "DATA-UP",
            timestamp: 7,
            payload: hexToArrayBuffer([
                "0xa1",
                "0x02",
                "0x03",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
                "0x04",
            ]),
        },
        {
            type: "USER-HINT",
            timestamp: 8,
            payload: "Woah guys this is a message",
        },
        {
            type: "DATA-DOWN",
            timestamp: 9,
            payload: hexToArrayBuffer([
                "0x44",
                "0x52",
                "0x4f",
                "0x4e",
                "0x45",
                "0x20",
                "0x54",
                "0x45",
                "0x53",
                "0x54",
                "0x49",
                "0x4e",
                "0x47",
                "0x20",
                "0x46",
                "0x4c",
                "0x49",
                "0x47",
                "0x48",
                "0x54",
                "0x75",
                "0x77",
                "0x68",
                "0x64",
                "0x71",
                "0x75",
                "0x6f",
                "0x70",
                "0x6e",
                "0x77",
                "0x70",
                "0x75",
                "0x64",
                "0x55",
                "0x41",
                "0x53",
                "0x77",
                "0x71",
                "0x75",
                "0x6e",
                "0x64",
                "0x75",
                "0x71",
                "0x77",
                "0x75",
                "0x75",
                "0x55",
                "0x4e",
                "0x45",
                "0x52",
                "0x53",
                "0x54",
                "0x41",
                "0x4e",
                "0x44",
                "0x20",
                "0x4d",
                "0x45",
                "0x3f",
                "0x3f",
                "0x3f",
                "0x32",
                "0x33",
                "0x31",
                "0x31",
                "0x32",
                "0x33",
            ]),
        },
    ];
}
